AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'db/structure.sql'
    - 'config/*'
    - 'lib/tasks/*'
    - 'public/*'
    - 'test/*'
